### ISSUE TITLE
Update METbaseimage to install the YAML Python package

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METbaseimage#15]
## Describe the Enhancement ##
https://github.com/dtcenter/MET/issues/2550 adds new dependency on the YAML Python package. The TC-Diag tool calls newly added Python diagnostics code which require YAML. This issue is to update METbaseimage to install YAML.

Recommend combining this change with #13 to create a single new tagged version of METbaseimage.

### Time Estimate ###
1 hour

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2770043

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required: Recommend having @DanielAdriaansen review the PR to keep him aware of Python-related updates.

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No additional impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Manually built on my laptop using the following commands:
```
bash
cd /Volumes/d1/projects/METbaseimage/.github/jobs
export GITHUB_WORKSPACE=/Volumes/d1/projects/METbaseimage
export GITHUB_TAG=v3.1
export DOCKERHUB_BASE_REPO=dtcenter/met-base
export DOCKERHUB_UNIT_TEST_REPO=dtcenter/met-base-unit-test
./build_docker_image.sh
```
Pushed the resulting images to DockerHub for testing with the dtcenter/MET#2728 pull request.
```
docker push dtcenter/met-base:v3.1
docker push dtcenter/met-base-unit-test:v3.1
```
Note that these manually created v3.1 images will be replaced by GHA when we actually create the official v3.1 METbaseimage release.
