### ISSUE TITLE
Create a `dtcenter/met-base-metviewer` image to make it suitable for METviewer development and testing

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METbaseimage#23]
## Describe the New Feature ##
Issue dtcenter/METviewer#521 adds automated SonarQube scanning of the METviewer software based on Air Force requirements. This work is done by first building METviewer inside of a Docker container and copying/scanning the resulting distribution files. This approach works well. However, the `docker build` step takes way too long. The Dockerfiles in METviewer still use centos7 as the base image and build the environment from scratch.

This issue is to update the existing METbaseimage environment so it can be used as the base image for METviewer Docker builds. Note, prior to merging the resulting PR, we should assess whether or not these changes bloat the size of METbaseimage too much. If so, we could consider creating a new METviewerbaseimage instead.

### Acceptance Testing ###
Work on this in conjunction with dtcenter/METviewer#521.
Test that issue using a METbaseimage branch for this feature.

### Time Estimate ###
1-2 days?

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED CYCLE ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
- [x] Closely related to dtcenter/METviewer#521

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
