### ISSUE TITLE
Enhance the MET base image to support NetCDF files using groups in the enhanced data model

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/METbaseimage#6]
## Describe the Enhancement ##
Pull request dtcenter/MET#2307 for issue dtcenter/MET#2068 adds a new test to unit_ioda2nc.xml that uses a new NetCDF input file:
```
https://dtcenter.ucar.edu/dfiles/code/METplus/MET/MET_unit_test/develop/unit_test/obs_data/ioda/2021081612_sonde_small.nc
```
That NetCDF file makes use of groups in the enhanced data model. While the NetCDF libraries on the primary development machine, seneca, can process that data file just fine, the METbaseimage NetCDF library errors out. The easiest way to demonstrate is running:
```
mkdir -p ioda; cd ioda
wget https://dtcenter.ucar.edu/dfiles/code/METplus/MET/MET_unit_test/develop/unit_test/obs_data/ioda/2021081612_sonde_small.nc
cd ..
docker run -it --rm -v `pwd`/ioda:/ioda dtcenter/met-base:v1.0 ncdump -h /ioda/2021081612_sonde_small.nc
```
That errors out:
```
ncdump: /ioda/2021081612_sonde_small.nc: NetCDF: HDF error
```
This issue is to update the NetCDF and/or HDF5 builds in METbaseimage to handle this flavor of NetCDF.

Recommend referring to RAL-IT details:
```
cat /usr/local/src/netcdf/README.snat /usr/local/src/hdf/hdf5/README.ral-it
```
Also recommend upgrading to NetCDF-4.7.4 and HDF5-1.10.6 to match the versions used on WCOSS2. 

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required: No scientist needed

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts anticipated.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.
